import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header/Header";
import ProgressBar from "@/components/ProgressBar/ProgressBar";

const golos = Golos_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${golos.className} text-foreground bg-background`}>
        <Providers>
          <Header />
          <ProgressBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
