name: CI/CD Pipeline

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  lint-client:
    name: Lint Client (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-node-

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Run lint
        working-directory: client
        run: npm run lint

  build-client:
    name: Build Client (Frontend)
    runs-on: ubuntu-latest
    needs: lint-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

  build-server:
    name: Build Server (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Build server
        working-directory: server
        run: npm run build

      - name: Create .env.local file on server
        run: |
          echo ${{ secrets.CLIENT_ENV }} | base64 -d > client/.env.local

  deploy-client:
    name: Deploy Client (Frontend) to MyDevil
    runs-on: ubuntu-latest
    needs: build-client
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to MyDevil
        run: |
          rsync -avz --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.env.local' ./client/ filip440@s62.mydevil.net:/usr/home/domains/${{ vars.FRONTEND_DOMAIN }}/public_nodejs/

  deploy-server:
    name: Deploy Server (Backend) to MyDevil
    runs-on: ubuntu-latest
    needs: build-server
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file on server
        run: |
          echo ${{ secrets.SERVER_ENV }} | base64 -d > server/.env

      - name: Deploy to MyDevil
        run: |
          rsync -avz --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.env' ./server/ filip440@s62.mydevil.net:/usr/home/domains/${{ vars.SERVER_DOMAIN }}/
